### ISSUE TITLE
When adding more than one file it duplicates the last file given

### ISSUE THREAD

**Issue by cquinn930** [Gebrel07/pymtom-xop#1] opened 2024-03-13 12:44 UTC
Hello, 

 When running the MtomAttachment(file=filename) in a for loop and appeding to a list it overwrites the first file given and duplicates the last. 

`from pymtom_xop import MtomAttachment, MtomTransport

procfiles = ["file1.pdf", "file2.pdf"]
mtom_attachments = []
for p in procfiles:
    t = MtomAttachment(file=p)
    mtom_attachments.append(t)

for row in mtom_attachments:
    print(row.file_name) `

file2.pdf
file2.pdf

**Comment by Gebrel07** [comment] 2024-03-13 21:21
nice catch, I'll check it out

**Comment by Gebrel07** [comment] 2024-03-14 01:44
Error was caused by classmethod decorators during initialization of MtomAttachmens.
Fixed in release 0.0.2, please try this version.

**Comment by Gebrel07** [comment] 2024-03-14 01:44
Error was caused by classmethod decorators during initialization of MtomAttachments.
Fixed in release 0.0.2, please try this version.

**Closed as completed by Gebrel07** 2024-03-14 01:44 UTC
Labels: bug
